language: python
python:
  - "2.7"
install:
  - "pip install -U pip --use-mirrors"
  - "pip install -U -r requirements-test.txt coverage --use-mirrors"
script: nosetests -v --with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=coal
